package com.app.master.service.core.response;

public enum ResponseCode {

    INTERNAL_ERROR,
    ACCESS_DENIED,
    USER_NOT_FOUND,
    USER_ALREADY_EXIST,
    BAD_REQUEST,
    NOT_FOUND,
    CREATED,
    SERVICE_UNAVAILABLE,
    UNAUTHORIZED,
    DB_ERROR,
    IAM_ERROR,
    AWS_ERROR,
    ENTITY,
    OK,
    UPDATED,
    UNSUPPORTED_MEDIA_TYPE,
    CUSTOM_FORM_CREATED,
    CUSTOM_FORM_UPDATED,
    CUSTOM_FORM_DELETED,
    CUSTOM_FORM_STATUS_CHANGED,
    FORM_DATA_GET_SUCCESSFULLY,
    DELETED,
    FETCHED,
    UPLOADED,
    CONFLICT,
    GENERIC_ERROR,
    ALREADY_EXIST,
    IMPORTED,
    SYNCED
}