databaseChangeLog:
  - changeSet:
      id: create_product_intent_table
      author: admin
      changes:
        - createTable:
            tableName: product_intent
            columns:
              - column:
                  name: id
                  type: bigint
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: uuid
                  type: uuid
                  defaultValueComputed: gen_random_uuid()
                  constraints:
                    nullable: false
                    unique: true
              - column:
                  name: product_uuid
                  type: uuid
                  constraints:
                    nullable: false
              - column:
                  name: customer_id
                  type: varchar(255)
                  constraints:
                    nullable: false
              - column:
                  name: created_at
                  type: timestamp
                  defaultValueComputed: NOW()
                  constraints:
                    nullable: false
              - column:
                  name: archive
                  type: boolean
                  defaultValueBoolean: false
                  constraints:
                    nullable: false
        - createIndex:
            indexName: idx_product_intent_product_uuid
            tableName: product_intent
            columns:
              - column:
                  name: product_uuid
