package com.app.master.service.controller.client;

import com.app.master.service.core.controller.AppController;
import com.app.master.service.core.entity.PaymentAttemptEntity;
import com.app.master.service.core.exception.VeloriaException;
import com.app.master.service.core.payment.CancellationActor;
import com.app.master.service.core.payment.CancellationReason;
import com.app.master.service.core.response.Response;
import com.app.master.service.core.response.ResponseCode;
import com.app.master.service.service.admin.impl.SalesOrderServiceImpl;
import com.app.master.service.service.client.ClientSessionStore;
import com.app.master.service.service.payment.PaymentService;
import com.app.master.service.service.payment.PaymentWebhookService;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotBlank;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.Setter;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Payment endpoints for a signed-in shopper.
 *
 * <p>Every endpoint except the webhook requires the customer's session token and
 * acts only on that customer's own orders; the service checks ownership again
 * rather than trusting the controller to have done so.
 *
 * <p>The webhook is the exception, and deliberately so: it comes from Razorpay,
 * not from a browser, and carries no session. It is authenticated by its
 * signature instead, which is verified before its body is read.
 */
@RestController
@CrossOrigin(origins = {"*"})
@RequestMapping("/api/master/client")
@RequiredArgsConstructor
@Slf4j
public class ClientPaymentController extends AppController {

    private final PaymentService paymentService;
    private final PaymentWebhookService webhookService;
    private final SalesOrderServiceImpl orderService;
    private final ClientSessionStore sessionStore;

    // ── initiation ───────────────────────────────────────────────────────────

    @Getter @Setter
    public static class InitiateRequest {
        @NotBlank(message = "orderCode is required")
        private String orderCode;

        /** ONLINE_FULL, ONLINE_PARTIAL or COD. */
        @NotBlank(message = "paymentMode is required")
        private String paymentMode;

        /**
         * One value per attempt to pay, generated by the browser and reused on
         * retry. Deliberately not the order's checkout reference: one order can
         * need several payments, and reusing that would make the second look
         * like a duplicate of the first.
         */
        @NotBlank(message = "idempotencyKey is required")
        private String idempotencyKey;

        /**
         * Present only so a client that sends it gets a clear refusal rather
         * than silently having it ignored. The server computes the amount from
         * the order; a browser does not get to say what it owes.
         */
        private Long amount;
    }

    /**
     * Prepares a payment and returns what Checkout needs to open.
     *
     * <p>The response carries the publishable key id, never the secret.
     */
    @PostMapping("/payment/initiate")
    public ResponseEntity<Response> initiate(
            @RequestHeader("Authorization") String authHeader,
            @Valid @RequestBody InitiateRequest request) throws VeloriaException {

        if (request.getAmount() != null) {
            throw new VeloriaException(ResponseCode.BAD_REQUEST,
                    "The payment amount is determined by the server and must not be supplied.");
        }

        String token = token(authHeader);
        PaymentService.CheckoutSession session = paymentService.initiate(
                token, request.getOrderCode(), request.getPaymentMode(), request.getIdempotencyKey());

        Map<String, Object> body = new LinkedHashMap<>();
        body.put("paymentId", session.attemptUuid());
        body.put("orderCode", session.orderCode());
        body.put("amount", session.amountPaise());
        body.put("currency", session.currency());
        body.put("cashOnDelivery", session.cashOnDelivery());
        if (!session.cashOnDelivery()) {
            body.put("razorpayKeyId", session.razorpayKeyId());
            body.put("razorpayOrderId", session.razorpayOrderId());
        }
        return success(ResponseCode.OK, "Payment initiated", body);
    }

    // ── verification ─────────────────────────────────────────────────────────

    @Getter @Setter
    public static class VerifyRequest {
        @NotBlank private String razorpayOrderId;
        @NotBlank private String razorpayPaymentId;
        @NotBlank private String razorpaySignature;
    }

    /**
     * Confirms a payment the Checkout callback has just reported.
     *
     * <p>A success here means the backend has re-read the payment from Razorpay
     * and found it captured for the right amount. The browser's own success
     * callback is not sufficient and is never treated as such.
     */
    @PostMapping("/payment/verify")
    public ResponseEntity<Response> verify(
            @RequestHeader("Authorization") String authHeader,
            @Valid @RequestBody VerifyRequest request) throws VeloriaException {

        PaymentAttemptEntity attempt = paymentService.verify(
                token(authHeader), request.getRazorpayOrderId(),
                request.getRazorpayPaymentId(), request.getRazorpaySignature());

        Map<String, Object> body = new LinkedHashMap<>();
        body.put("paymentId", attempt.getUuid());
        body.put("orderCode", attempt.getOrderCode());
        body.put("status", attempt.getStatus());
        body.put("amount", attempt.getAmountPaise());
        return success(ResponseCode.OK, "Payment verified", body);
    }

    /** What the shopper has paid for one of their orders, and what is still due. */
    @GetMapping("/payment/order/{orderCode}")
    public ResponseEntity<Response> paymentsForOrder(
            @RequestHeader("Authorization") String authHeader,
            @PathVariable String orderCode) throws VeloriaException {
        return success(ResponseCode.FETCHED, "Payments fetched",
                paymentService.summaryFor(token(authHeader), orderCode));
    }

    // ── customer cancellation ────────────────────────────────────────────────

    @Getter @Setter
    public static class CancelRequest {
        /** Optional for a customer; one of the approved reasons when supplied. */
        private String reason;
    }

    /**
     * Cancels the shopper's own order.
     *
     * <p>Permitted up to and including dispatch, and refused once the order is
     * out for delivery — at that point the parcel is with a courier and the
     * refusal or return route applies instead.
     */
    @PostMapping("/order/{orderCode}/cancel")
    public ResponseEntity<Response> cancelOwnOrder(
            @RequestHeader("Authorization") String authHeader,
            @PathVariable String orderCode,
            @RequestBody(required = false) CancelRequest request) throws VeloriaException {

        ClientSessionStore.SessionData session = sessionStore.get(token(authHeader));
        if (session == null) {
            throw new VeloriaException(ResponseCode.UNAUTHORIZED, "Session expired. Please sign in again.");
        }

        String raw = request == null ? null : request.getReason();
        orderService.cancelAs(orderCode, CancellationActor.CUSTOMER,
                CancellationReason.of(raw).orElse(CancellationReason.CUSTOMER_REQUEST),
                raw, session.userId());

        return success(ResponseCode.OK, "Order cancelled", null);
    }

    // ── webhook ──────────────────────────────────────────────────────────────

    /**
     * Razorpay's server-to-server notification.
     *
     * <p>Takes the body as a raw string on purpose: the signature is computed
     * over the exact bytes Razorpay sent, and letting Jackson parse and
     * re-serialise it would change them and break verification.
     *
     * <p>Always answers 200 once the signature has verified, even when the event
     * is one we do not act on. A non-2xx tells Razorpay to redeliver, and
     * redelivering an event that was understood and deliberately ignored
     * achieves nothing.
     */
    @PostMapping("/payment/webhook")
    public ResponseEntity<Response> webhook(
            @RequestBody String rawBody,
            @RequestHeader(value = "X-Razorpay-Signature", required = false) String signature,
            @RequestHeader(value = "X-Razorpay-Event-Id", required = false) String eventId)
            throws VeloriaException {

        PaymentWebhookService.Outcome outcome = webhookService.handle(rawBody, signature, eventId);
        return success(ResponseCode.OK, "Webhook " + outcome.name().toLowerCase(), null);
    }

    private static String token(String authHeader) {
        return authHeader == null ? "" : authHeader.replace("Bearer ", "").trim();
    }
}
